### ISSUE TITLE
old passwords

### ISSUE THREAD

**Issue by tossser** [ajartille/gumshoe#17]
Hello! Installed this extension (Gumshoe) more than a year ago and it successfully saved all the all passwords. After reinstalling the Chrome, this extension is installed automatically. But when I went to see the password list, only the new ones that were introduced after the reinstall of the browser were displayed. Can I see old passwords from sites?
The expansion is simply wonderful! 
Many thanks!

**Comment by ajartille** [comment]
I'm toying with the idea of trying to store this data (encrypted) in Google storage for persistence, not only in instances of reinstallation but also across devices. I'll be rolling out an update soon once I sort out encrypted storage for the information and look a little deeper into how to enable persistence.

Appreciate your interest. This is certainly on my to-do list, but very busy these days... 😅

**Comment by tossser** [comment]
`You can't recover that. Sorry.`
sad, but I **hope** that you will add support for the storage.
